### PR TITLE
Fix #293, #294, #296; Change kubectl port-forward command port and add sentence regarding use of 'open'

### LINKED ISSUE #293: Developer Concepts - Create a Pod - Issues
On Page: https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/developer-concepts

Issue 1:  Command in "Verify that the pod came up fine" use subshell (&) instead of chaining (&&)

Issue 2:  Port 8080 is a common local port that could likely be in use.  At least warn the user.

### PR DESCRIPTION
**Pull request by scottmalkie**
*Issue #, if available:* #293  #294 

*Description of changes:*
Refactor port-forward command to use 8088 instead of 8080 and also warn user to make sure port isn't in use.  Also added a sentence regarding lack of `open` support on certain distros.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by christopherhein** [comment]
Can we do two things, update the screenshot to be `8088` and can you also just move the `open` command to a second line?

**Comment by scottmalkie** [comment]
Added fix for #296 - changed yamls and instructions to be "nginx-deployment-ns" consistently throughout.

**Comment by scottmalkie** [comment]
@christopherhein Updated the image to reflect the port change and moved open to its own line.  Thanks!

**Comment by arun-gupta** [comment]
@christopherhein can you confirm this?

**Comment by christopherhein** [comment]
Awesome, merging.

**Pull request merged**
