### PR TITLE
fixed jsonpath of "get pod memory" example command

### PR DESCRIPTION
**Pull request by mpneuried**
*Issue #, if available:*

*Description of changes:*
Found a bug in an example command

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by arun-gupta** [comment]
@mpneuried Both commands give me the same output. What's the difference?

**Comment by christopherhein** [comment]
I get the same thing @arun-gupta - I want to say this is more on the stylistic side of things. kubernetes docs declare either should work for `jsonpath` parsing see row 3 in the 
functions table at the bottom - https://kubernetes.io/docs/reference/kubectl/jsonpath/

**Comment by arun-gupta** [comment]
Will stick with the existing style

**Comment by mpneuried** [comment]
In my case i was able to get the relevant data with `{.spec.containers..resources}` but not with `{.spec.containers[].resources}`

I made a screenshot:
bildschirmfoto 2017-12-08 um 08 13 17

It's running on a 2015 macbook pro running on minikube.

**Comment by christopherhein** [comment]
@mpneuried are you using zsh? or `fish` or is this `bash`?

**Comment by mpneuried** [comment]
In my case it‘s zsh with the popular „oh-my-zsh“ flavor.

**Pull request closed without merging**
